services:
  postgres:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  db_data:
