version: '3'

tasks:
  up:
    cmds:
      - docker compose up -d

  gen:
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent new {{ .MODEL }}
    requires:
      vars: [MODEL]

  ent:
    cmds:
      - go generate ./ent

  dev-db-create:
    cmds:
      - |
        docker compose exec {{ .DB_CONTAINER }} psql \
          -h 127.0.0.1 \
          -p 5432 \
          -U {{ .DB_USER }} \
          -c "CREATE DATABASE {{ .DB_NAME }}"
    vars:
      DB_CONTAINER: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: saas
