-- Create "organizations" table
CREATE TABLE "organizations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "organizations_name_key" to table: "organizations"
CREATE UNIQUE INDEX "organizations_name_key" ON "organizations" ("name");
-- Create "organization_users" table
CREATE TABLE "organization_users" (
  "organization_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("organization_id", "user_id"),
  CONSTRAINT "organization_users_organization_id" FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "organization_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
