name: test and coverage
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: saas_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Atlas
        run: |
          curl -sSf https://atlasgo.sh | sh

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
